use sakila;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE person MODIFY person_id SMALLINT UNSIGNED AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS=1;
desc person;

-- SET FOREIGN_KEY_CHECKS=0;を実行して、無理やり設定を変えているのは推奨されないらしい